### ISSUE TITLE
Why!

### ISSUE THREAD

**Issue by Innei** [syscl/Fix-usb-sleep#19]
cp: /tmp/sysclusbfix.wake: No such file or directory
![image](https://user-images.githubusercontent.com/41265413/52343916-6fa1b980-2a54-11e9-820f-acabe89dcd52.png)

**Comment by syscl** [comment]
Oh you should use sudo ./fixUSB.sh

**Comment by Innei** [comment]
But I used sudo ./fixUSB.sh now. Still Failed.
![image](https://user-images.githubusercontent.com/41265413/53145563-9bd44300-35db-11e9-8fea-a61436f5ca18.png)
