### ISSUE TITLE
开启此脚本以后会有一个cat占用CPU比较高

### ISSUE THREAD

**Issue by ypwhs** [syscl/Fix-usb-sleep#4]
![image](https://cloud.githubusercontent.com/assets/10473170/17277952/07de4b1c-5782-11e6-8f2b-3e38f8cdeee5.png)
![image](https://cloud.githubusercontent.com/assets/10473170/17277953/10accfca-5782-11e6-9fe8-8a1bd4242cfe.png)

非常感谢作者能够奉献自己的时间去解决这个睡眠问题。但是我这里跑这个脚本的时候CPU会保持一个比较高的频率，静息状态CPU是保持在1GHz运转的，希望能得到解决。

**Comment by ypwhs** [comment]
根本没有这个问题啦！原来脚本只需要运行一次就行了！哈哈哈！谢谢作者！！

**Comment by syscl** [comment]
@ypwhs 
感谢你的反馈, 能提供一下你执行这个脚本的截图吗, 因为这个脚本结束之后就退出了, 不应该会出现这样的情况啊, 所以需要你的进一步反馈 :)

--
Thanks for your feedback, please provide the screenshot after executing the script. Since, once the fix-usb-sleep has been finished, it will quit. So I need your further feedback :)

syscl

**Comment by ypwhs** [comment]
![image](https://cloud.githubusercontent.com/assets/10473170/17306671/d45a114e-5863-11e6-81bb-09be0e2f6e34.png)
之前有输出值，但是现在执行的时候已经没有输出了，cat进程仍然以将近100%的占用率在运行。

**Comment by syscl** [comment]
@ypwhs 这个终端好奇怪 我的执行也不是这种样子输出的.

试一下用调试模式输出吧
```sh
./fixUSB.sh -d
```

--
@ypwhs It seems that your terminate is not the default bash in OS X, and the output of my script is not the same as your screenshot post here.

try to use debug mode to see what's going on
```
./fixUSB.sh -d
```

syscl

**Comment by ypwhs** [comment]
![image](https://cloud.githubusercontent.com/assets/10473170/17332103/2c6c9658-5900-11e6-8d7a-01d12b3990c5.png)
在调试模式需要输入管理员密码，不过似乎有一些错误信息，之后可以正常退出。
在普通模式下依旧卡在cat上出不来。

**Comment by syscl** [comment]
@ypwhs 有用, 这个问题我在M3800最近的更新中也遇到了, 肯定是我有改动导致bug了, 我会尝试修复的.

感谢你的反馈;)

--
@ypwhs Thks, really valuable information. The same issue occurs on the recent update of my M3800 project, so I have to try to figure out what's wrong with the latest update. 

Again, thanks for your feedback;)
syscl

**Comment by syscl** [comment]
@ypwhs 尝试新的脚本;) 我已经修复了.

--
@ypwhs Try the latest script of fixUSB.sh;), I have fixed the issue.

syscl
