### ISSUE TITLE
At wake EFI partition mounts...

### ISSUE THREAD

**Issue by brousseau6933** [syscl/Fix-usb-sleep#5]
Hello,

Wonderful work, except that at wake, my external EFI partitions mounts on the desktop. How to stop it?

Thanks.

Patrice

BTW, real MacBook Pro Early 2011.

**Comment by syscl** [comment]
@brousseau6933 
Thanks for your tips, but at least, please provide some information for me, in terminal, type in
```sh
diskutil list
```

Thanks,
syscl

**Comment by brousseau6933** [comment]
Thanks,

As requested... but I uninstalled the script with sudo ./fixusb.sh -u and reinstalled but it doesn't work anymore. I am Clueless!!!

MACBOOKPRO-F58F:~ bpatrice$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            398.7 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:       Microsoft Basic Data BOOTCAMP                100.4 GB   disk0s4
/dev/disk1 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *3.0 TB     disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                  Apple_HFS Mavericks               999.7 GB   disk1s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk1s3
   4:                  Apple_HFS Pat                     800.0 GB   disk1s4
   5:                  Apple_HFS LACIE SHARE             1.2 TB     disk1s5
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS MAC                     500.1 GB   disk2s2
   3:       Microsoft Basic Data WINDOWS                 499.7 GB   disk2s3
/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *500.1 GB   disk3
   1:               Windows_NTFS Seagate Expansion Drive 500.1 GB   disk3s1

**Comment by syscl** [comment]
Do worry, I will try to fix it :)

Please paste the data as is, thanks.

syscl

**Comment by brousseau6933** [comment]
MACBOOKPRO-F58F:~ Studio$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macintosh HD            398.7 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:       Microsoft Basic Data BOOTCAMP                100.4 GB   disk0s4
/dev/disk1 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *3.0 TB     disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:                  Apple_HFS Mavericks               999.7 GB   disk1s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk1s3
   4:                  Apple_HFS Pat                     800.0 GB   disk1s4
   5:                  Apple_HFS LACIE SHARE             1.2 TB     disk1s5
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS MAC                     500.1 GB   disk2s2
   3:       Microsoft Basic Data WINDOWS                 499.7 GB   disk2s3
/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *500.1 GB   disk3
   1:               Windows_NTFS Seagate Expansion Drive 500.1 GB   disk3s1

**Comment by syscl** [comment]
@brousseau6933 
Try the latest update, I have rewritten the script to mount partitions which are unmounted during sleep. In that case, this script turns into a more flexible and acts accurately. Thanks for your tip which made this script much better.

BTW, as a reminder, I have since tested my external hard disk with EFI partition, by waking from sleep, there's no EFI partitions being mounted, so I think maybe there's something wrong in your hard disk. Just my guess. 

See if this update can solve your issue.
Thanks,
syscl
